### ISSUE TITLE
Any way to get around `absolute path`?

### ISSUE THREAD

**Issue by abravalheri** [tcmetzger/sphinx-favicon#1]
Hi @tcmetzger, thank you very much for the package. It is very useful.

I was wondering, is there anyway to get around the `absolute path` requirement?

Considering that [Sphinx currently copies everything inside the directories listed in `html_static_path` to `_static`](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=static#confval-html_static_path), couldn't we just use `/_static/<file name>` in the href?

**Comment by tcmetzger** [comment]
@abravalheri I'm glad to hear you find this package useful! You could probably use `/_static/<file name>`, but as far as I can see, this would only work with pages that are in the same directory. Once you start having RST files in subdirectories as well, the reference won't work anymore.
I'm sure there is a way to fix this - I just haven't had the time to research and implement that. Please feel free to make a PR if you can. Thanks!
