### ISSUE TITLE
is this lib still maintained ? 

### ISSUE THREAD

**Issue by 12rambau** [tcmetzger/sphinx-favicon#10]
I am one of the maintainer of the pydata-sphinx-theme. We are supporting inside our theme the same thing as you do here in sphinx-favicon.

You're lib seems super neat and does exactly the same thing (with the same configuration). So my question is super simple, if we drop this on our side and rely on your repository would tou be around to check the issues ? (I would for PR and stuff but I won't be able to merge them ;-) )

**Comment by tcmetzger** [comment]
Hey! Yes, that sounds great, I'm planning to be around!
