### ISSUE TITLE
could you change te name of the lib folder to sphinx_favicon ?

### ISSUE THREAD

**Issue by 12rambau** [tcmetzger/sphinx-favicon#11]
The folder containing the python package is currently `sphinx-favicon` which is not a legit python name. Most of the extention I know have usually a name with "-" and a folder with "_" like: "sphinx_copybutton", "sphinx_design", "jupyter_sphinx", "sphinx_design". 

I was working on the mypy issue to but it's not working as "sphinx-favicon" is not a legit python name.

**Comment by tcmetzger** [comment]
You are absolutely right, it should be `sphinx_favicon`! Do you want to make a PR, while you are at it? If not, I'll try to make one in the next few days!
