### ISSUE TITLE
do you want to create a sphinx single page documentation ? 

### ISSUE THREAD

**Issue by 12rambau** [tcmetzger/sphinx-favicon#12]
I saw sphinx in the dev-requirements.txt file and I was curious if you wanted to use it ?

**Comment by tcmetzger** [comment]
That is a very good idea - the dependency is in there because I started doing that a while ago but never finished! 😅

**Comment by 12rambau** [comment]
would you prefer to use github pages or readthedocs ?

**Comment by tcmetzger** [comment]
I usually use readthedocs!

**Comment by tcmetzger** [comment]
To Dos:

- [x] Create docs
- [x] deploy to readthedocs
- [x] add docs badge and link to readme and repo
