### ISSUE TITLE
Update changelog for 1.0 release

### ISSUE THREAD

**Issue by tcmetzger** [tcmetzger/sphinx-favicon#16]
Changelog needs to be updated

**Comment by 12rambau** [comment]
An easy way to get an "alway up to date" changelog is to always use PR to make changes. If you do, GitHub can auto-generate the changelog between 2 releases (e.g: https://github.com/pydata/pydata-sphinx-theme/releases/tag/v0.12.0)

**Comment by tcmetzger** [comment]
With all those updates and new features (and the breaking change), this warrants a new major version number!

Remaining todos:

- [ ] Update docs and banner for v.1.0
- [ ] Update Changelog (us automatic GH process)
- [ ] tag and publish the release

**Comment by tcmetzger** [comment]
@12rambau can you think of anything else that needs to get done for this release?

**Comment by 12rambau** [comment]
that seems just fine !
