### ISSUE TITLE
use a favicon in the docs ? 

### ISSUE THREAD

**Issue by 12rambau** [tcmetzger/sphinx-favicon#21]
I was thinking of using the doc as a small demo using the sphinx-contrib logo https://avatars.githubusercontent.com/u/31936682?s=200&v=4. 

I have a small favicon generator to get all the format at once

Bonus: I would like to change the theme for pydata-sphinx-theme and explain how to use `nox` in the contribution section

**Comment by tcmetzger** [comment]
Using that icon is a great idea! I didn't really have an idea for what logo to use, so this would be perfect 😀
You can absolutely also switch to the pydata-sphinx-theme!
