### ISSUE TITLE
build the documentation on PR

### ISSUE THREAD

**Issue by 12rambau** [tcmetzger/sphinx-favicon#28]
Now that there is a readthedocs build of the documentation would it be possible to activate the build of PR ? 

Only the maintainer of the doc (@tcmetzger) can do it from the project parameters. Please see this documentation for more information: https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by tcmetzger** [comment]
Thanks! I followed the four steps in https://docs.readthedocs.io/en/stable/pull-requests.html#configuration - please let me know if this works as intended!

**Comment by 12rambau** [comment]
documentation was automatically build for https://github.com/tcmetzger/sphinx-favicon/pull/30. Everything work like expected
