### ISSUE TITLE
Static paths contain unnecessary repetitions

### ISSUE THREAD

**Issue by tcmetzger** [tcmetzger/sphinx-favicon#45]
When using a static image, the paths sometime contain unnecessary repetitions of `_static`. eg:

```
<link href="_static/_static/_static/favicon-32x32.png" sizes="32x32" rel="icon" type="image/png">
<link href="_static/favicon-16x16.png" sizes="16x16" rel="icon" type="image/png">
<link rel="shortcut icon" sizes="any" href="_static/_static/_static/favicon.ico" type="image/x-icon">
<link href="_static/android-chrome-192x192.png" sizes="192x192" rel="icon" type="image/png">
<link rel="mask-icon" color="#2d89ef" href="_static/_static/_static/safari-pinned-tab.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="_static/_static/_static/apple-touch-icon.png" sizes="180x180" type="image/png">
```

**Comment by tcmetzger** [comment]
This bug appears in our own docs after https://github.com/tcmetzger/sphinx-favicon/pull/35 - i.e. after we introduce `sphinx-design` and after we start using multiple pages.
This might be some sort of issue in connection with sphinx-design. Or, more likely, it might have to do with having multiple pages...

**Comment by 12rambau** [comment]
I thinks it's a bug from `pathto` method and how we use it. It will require a patch release sorry
