### ISSUE TITLE
Add `conda-forge` Recipe

### ISSUE THREAD

**Issue by michaelweinold** [tcmetzger/sphinx-favicon#53]
I saw that the `pydata-sphinx-theme` has [deprecated their favicon option](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/branding.html#add-favicons), instead suggesting this package be used.

I was [unable to find a conda-forge feedstock](https://github.com/orgs/conda-forge/repositories?q=favicon&type=all&language=&sort=) for `sphinx_favicon` - could you add one (otherwise [it's the only package we would need to install using pip](https://github.com/brightway-lca/brightway-documentation/blob/main/conda_environment.yml)?

If you're suuuper busy, I could set up the feedstock repo in the coming weeks.

**Comment by 12rambau** [comment]
the recipe request is done https://github.com/conda-forge/staged-recipes/pull/22472, I now need few verifications from @tcmetzger and the conda-forge team.

**Comment by tcmetzger** [comment]
@michaelweinold Thanks for bringing this up, and thanks @12rambau for getting this ball rolling so quickly!
