### ISSUE TITLE
Add suport for rel="manifest" icons (site.webmanifest)

### ISSUE THREAD

**Issue by tcmetzger** [tcmetzger/sphinx-favicon#6]
https://developer.mozilla.org/en-US/docs/Web/Manifest/icons

**Comment by 12rambau** [comment]
If you set 
```python
{"rel": "manifest", "static-file": "favicon/site.webmanifest"},
```

it's already working right ? 

At least from my side I get the expected html:
```html 
<link rel="manifest" href="_static/favicon/site.webmanifest">
```

as most of the favicon generator are generating the file for you, I don't think you need to go any further than that
