### ISSUE TITLE
 Add `sphinx-extension` GitHub topic

### ISSUE THREAD

**Issue by astrojuanlu** [tcmetzger/sphinx-favicon#9]
Hi! I arrived here from https://github.com/sphinx-doc/sphinx/issues/9861. I usually browse https://github.com/topics/sphinx-extension to discover new extensions, would be great to have this extension listed there :)

**Comment by tcmetzger** [comment]
@astrojuanlu Thanks, that is an excellent idea! I added some tags and hope that GitHub will pick those up soon. Let me know if you have any more ideas on how to let people know about this extension! 😀

**Comment by astrojuanlu** [comment]
You can also send a PR here! https://github.com/humitos/sphinx-extensions/
